#!/usr/bin/env python3
"""Extract a screen-friendly ECDICT review set in the project wordlist syntax.

ECDICT is MIT-licensed by its repository. This tool does not download it: obtain
its CSV yourself, review the upstream license, then choose an output path. The
output is deliberately a *candidate* set: ECDICT supplies no example sentences
and its glosses need human review before becoming built-in learning cards.
"""

import argparse
import csv
import sys
from pathlib import Path


LICENSE_NOTE = """/*
 * Generated by tools/extract_ecdict.py from ECDICT (MIT License).
 * Upstream: https://github.com/skywind3000/ECDICT
 * Keep ECDICT's LICENSE with any redistributed generated word list.
 */"""


def clean(text: str) -> str:
    return " ".join(text.replace("\\n", "; ").replace("|", "/").split())


# The device renderer has explicit glyph coverage rather than generic Unicode support.
# Keep this in sync with lib/vocab/vocab.cpp's kPhoneticWhitelist.
IPA_ALLOWED = set("/'-. ˈˌːiueoaɪɛæɑɒɔʊʌəɜɚpbtdkgfvszhmnlrjwθðʃʒŋɹɾ")


def normalize_phonetic(phonetic: str) -> str:
    # ECDICT uses U+04D9 for schwa and ASCII ':' for IPA length in many rows.
    # Both are normalized to code points that the on-device IPA renderer supports.
    return clean(phonetic).replace("ә", "ə").replace(":", "ː")


def has_supported_phonetic(phonetic: str) -> bool:
    return bool(phonetic) and all(char in IPA_ALLOWED for char in phonetic)


def cpp_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def is_candidate(row: dict[str, str], max_rank: int, max_definition_chars: int) -> bool:
    word = row["word"].strip()
    phonetic = normalize_phonetic(row["phonetic"])
    definition = clean(row["definition"])
    try:
        frequency = int(row["frq"].strip() or 0)
    except ValueError:
        return False

    return (
        word.isascii()
        and word.isalpha()
        and word.islower()
        and has_supported_phonetic(phonetic)
        and bool(definition)
        and 0 < frequency <= max_rank
        and len(definition) <= max_definition_chars
    )


def render(rows: list[dict[str, str]]) -> str:
    lines = [
        LICENSE_NOTE,
        "",
        "// Candidate cards only: review definitions and add examples before shipping.",
        '#include "wordlist.h"',
        "",
        "namespace vocab {",
        "",
        "const char *kRawWords =",
    ]
    for row in rows:
        word = cpp_escape(row["word"].strip())
        phonetic = cpp_escape(normalize_phonetic(row["phonetic"]))
        definition = cpp_escape(clean(row["definition"]))
        lines.append(f'    "{word} | {phonetic} | {definition}\\n"')
    lines.extend(
        [
            "    ;",
            "",
            f"const size_t kExpectedWordCount = {len(rows)};",
            "",
            "}  // namespace vocab",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="path to upstream ecdict.csv")
    parser.add_argument(
        "--output", type=Path, required=True, help="generated candidate C++ file"
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=500,
        help="maximum number of entries (default: 500)",
    )
    parser.add_argument(
        "--max-rank",
        type=int,
        default=10000,
        help="maximum ECDICT frq rank (default: 10000)",
    )
    parser.add_argument(
        "--max-definition-chars",
        type=int,
        default=120,
        help="maximum normalized definition length (default: 120)",
    )
    args = parser.parse_args()

    if args.limit < 1 or args.max_rank < 1 or args.max_definition_chars < 1:
        parser.error("--limit, --max-rank, and --max-definition-chars must be positive")

    csv.field_size_limit(sys.maxsize)
    with args.input.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        required = {"word", "phonetic", "definition", "frq"}
        if not reader.fieldnames or not required.issubset(reader.fieldnames):
            parser.error(
                "input is not an ECDICT CSV with word, phonetic, definition, and frq columns"
            )
        candidates = [
            row
            for row in reader
            if is_candidate(row, args.max_rank, args.max_definition_chars)
        ]

    candidates.sort(key=lambda row: int(row["frq"].strip()))
    selected = candidates[: args.limit]
    if not selected:
        parser.error("no entries match the requested filters")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(selected), encoding="utf-8")
    print(f"wrote {len(selected)} entries to {args.output}")
    print(f"selected from {len(candidates)} candidates (frq <= {args.max_rank})")


if __name__ == "__main__":
    main()
